In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv("diabetes.csv")

In [ ]:
dados = {
    "nome": ["Ana", "Bruno", "Carlos", "Diana", "Eduardo", "Filipa"],
    "idade": [22, 25, 21, 24, 23, 26],
    "curso": ["Python", "Java", "Python", "C#", "Python", "Java"],
    "nota": [17, 14, 12, 18, 10, 16],
    "horas_estudo": [20, 15, 10, 25, 8, 18]
}

In [ ]:
_ = pd.DataFrame(dados)

In [ ]:
df.head()

In [ ]:
df.tail()

In [ ]:
df.info()

In [ ]:
df.dtypes

In [ ]:
df2 = pd.read_csv("client_hostname.csv")
df2.head()

In [ ]:
df2.dtypes

In [ ]:
df2.info()

In [ ]:
df.describe()

In [ ]:
df2.describe()

In [ ]:
df.shape

In [ ]:
df2.shape

In [ ]:
df.columns

In [ ]:
df.index

In [ ]:
type(df)

In [ ]:
df.Age

In [ ]:
df["Age"]

In [ ]:
df2 = pd.read_csv("client_hostname.csv")
df2.head()

In [ ]:
alList = df2["alias list"]

In [ ]:
type(alList)

In [ ]:
df.Age.min()

In [ ]:
df.Age.max()

In [ ]:
df.Age.mean()

In [ ]:
df.Age.std()

In [ ]:
df.Age.sum()

In [ ]:
df.max()

In [ ]:
df2.nunique()

In [ ]:
df2.address_list.nunique()

In [ ]:
df2["alias list"].unique().tolist()

In [ ]:
pd.Series(df2["alias list"].unique())

In [ ]:
df2["alias list"].value_counts()

In [ ]:
df2.value_counts()

In [121]:
dados = {
    "nome": ["Ana", "Bruno", "Carlos", "Diana", "Eduardo", "Filipa"],
    "idade": [22, 25, 21, 24, 23, 26],
    "curso": ["Python", "Java", "Python", "C#", "Python", "Java"],
    "nota": [17, 14, 12, 18, 10, 16],
    "horas_estudo": [20, 15, 10, 25, 8, 18]
}
df = pd.DataFrame(dados)

In [73]:
df

      nome  idade   curso  nota  horas_estudo
0      Ana     22  Python    17            20
1    Bruno     25    Java    14            15
2   Carlos     21  Python    12            10
3    Diana     24      C#    18            25
4  Eduardo     23  Python    10             8
5   Filipa     26    Java    16            18

In [ ]:
df[["idade", "nome"]]

In [81]:
type(df[["idade"]])

pandas.DataFrame

In [ ]:
type(df["idade"])

In [89]:
df.iloc[0:4, 1:3]

   idade   curso
0     22  Python
1     25    Java
2     21  Python
3     24      C#

In [94]:
type(df.iloc[[1,3,5], [0, 3]])

pandas.DataFrame

In [95]:
type(df.iloc[[1], [0]])

pandas.DataFrame

In [96]:
type(df.iloc[1, 0])

str

In [98]:
df.iloc[[1,2,5]]

     nome  idade   curso  nota  horas_estudo
1   Bruno     25    Java    14            15
2  Carlos     21  Python    12            10
5  Filipa     26    Java    16            18

In [101]:
df.loc[[2, 1,5], ["nome","nota"]]

     nome  nota
2  Carlos    12
1   Bruno    14
5  Filipa    16

In [104]:
df[df.nota > 15]

     nome  idade   curso  nota  horas_estudo
0     Ana     22  Python    17            20
3   Diana     24      C#    18            25
5  Filipa     26    Java    16            18

In [107]:
df[(df.nota > 15) & (df.horas_estudo < 20) ]

     nome  idade curso  nota  horas_estudo
5  Filipa     26  Java    16            18

In [109]:
df[(df.nota > 15) | (df.horas_estudo < 11) ]

      nome  idade   curso  nota  horas_estudo
0      Ana     22  Python    17            20
2   Carlos     21  Python    12            10
3    Diana     24      C#    18            25
4  Eduardo     23  Python    10             8
5   Filipa     26    Java    16            18

In [112]:
df[(df.curso == "Java") | (df.curso == "C#") ]

     nome  idade curso  nota  horas_estudo
1   Bruno     25  Java    14            15
3   Diana     24    C#    18            25
5  Filipa     26  Java    16            18

In [124]:
df.sort_values("horas_estudo", ascending=False ,inplace=True)

In [125]:
df

      nome  idade   curso  nota  horas_estudo
3    Diana     24      C#    18            25
0      Ana     22  Python    17            20
5   Filipa     26    Java    16            18
1    Bruno     25    Java    14            15
2   Carlos     21  Python    12            10
4  Eduardo     23  Python    10             8

In [126]:
df.sort_values(["curso", "nota"], ascending=(False, True))

      nome  idade   curso  nota  horas_estudo
4  Eduardo     23  Python    10             8
2   Carlos     21  Python    12            10
0      Ana     22  Python    17            20
1    Bruno     25    Java    14            15
5   Filipa     26    Java    16            18
3    Diana     24      C#    18            25

In [127]:
df.sort_index(inplace=True)
df

      nome  idade   curso  nota  horas_estudo
0      Ana     22  Python    17            20
1    Bruno     25    Java    14            15
2   Carlos     21  Python    12            10
3    Diana     24      C#    18            25
4  Eduardo     23  Python    10             8
5   Filipa     26    Java    16            18