In [159]:
import pandas as pd
from utils import tratar_linha

In [160]:
raw_data_file = "Proxifier_2k.log"

In [161]:
linha = "[10.30 20:55:49] Yodao-Dict.exe - oimagea5.ydstatic.com:80 error : A connection request was canceled before the completion. "

tratar_linha(linha, 2025)

'2025.10.30 20:55:49;Yodao-Dict.exe;oimagea5.ydstatic.com:80;error;A connection request was canceled before the completion. '

In [162]:
with open(raw_data_file, "r") as origem, open("log.csv", "w") as destino:
    for linha in origem:
        destino.write(tratar_linha(linha))

In [163]:
df = pd.read_csv("log.csv",
                 sep=";",
                 names=["Data", "App","URL_Port","Status", "msg"],
                index_col=False
                 )
df.head()

,Data,App,URL_Port,Status,msg
0,2015.10.30 16:49:06,chrome.exe,proxy.cse.cuhk.edu.hk:5070,open,through proxy proxy.cse.cuhk.edu.hk:5070 HTTPS
1,2015.10.30 16:49:06,chrome.exe,proxy.cse.cuhk.edu.hk:5070,open,through proxy proxy.cse.cuhk.edu.hk:5070 HTTPS
2,2015.10.30 16:49:06,chrome.exe,proxy.cse.cuhk.edu.hk:5070,open,through proxy proxy.cse.cuhk.edu.hk:5070 HTTPS
3,2015.10.30 16:49:07,chrome.exe,proxy.cse.cuhk.edu.hk:5070,close,"0 bytes sent, 0 bytes received, lifetime 00:01"
4,2015.10.30 16:49:07,chrome.exe,proxy.cse.cuhk.edu.hk:5070,open,through proxy proxy.cse.cuhk.edu.hk:5070 HTTPS

In [164]:
df.dtypes

Data        str
App         str
URL_Port    str
Status      str
msg         str
dtype: object

In [165]:
df.Data = pd.to_datetime(df.Data, format="%Y.%m.%d %H:%M:%S")

In [166]:
df.head(2)

,Data,App,URL_Port,Status,msg
0,2015-10-30 16:49:06,chrome.exe,proxy.cse.cuhk.edu.hk:5070,open,through proxy proxy.cse.cuhk.edu.hk:5070 HTTPS
1,2015-10-30 16:49:06,chrome.exe,proxy.cse.cuhk.edu.hk:5070,open,through proxy proxy.cse.cuhk.edu.hk:5070 HTTPS

In [167]:
df.dtypes

Data        datetime64[us]
App                    str
URL_Port               str
Status                 str
msg                    str
dtype: object

In [168]:
df.Status.unique()

<StringArray>
['open', 'close', 'error']
Length: 3, dtype: str

In [169]:
df[df.Status == '-']

Empty DataFrame
Columns: [Data, App, URL_Port, Status, msg]
Index: []

'chrome.exe *64 <=> 'chrome.exe

In [170]:
df.App.unique()

<StringArray>
[                      'chrome.exe',                  'svchost.exe *64',
                      'Dropbox.exe',                          'Wiz.exe',
                       'WeChat.exe',                        'putty.exe',
                   'SogouCloud.exe',                           'QQ.exe',
                    'YodaoDict.exe',                'SGPicFaceTool.exe',
                   'QQExternal.exe',                      'firefox.exe',
             'git-remote-https.exe', 'FlashPlayerPlugin_18_0_0_209.exe',
                       'GitHub.exe',                        'Skype.exe',
                  'spoolsv.exe *64',                     'AcroRd32.exe',
                   'chrome.exe *64',                       'SGTool.exe',
                      'Acrobat.exe',                    'MobaXterm.exe',
                 'GoogleUpdate.exe',           'TeamViewer_Service.exe',
            'HiSuiteDownLoader.exe',                        '360AP.exe',
                    'tencentdl.exe',                     'QQPlayer.exe',
                'BSvcProcessor.exe',              'msfeedssync.exe *64',
                 'QQProtectUpd.exe',                     'SohuNews.exe']
Length: 32, dtype: str

In [171]:
def arq(app:str, sep="*"):
    if app.__contains__(sep):
        aux = app.split(sep)
        return aux[0], aux[1]
    else:
        return app, 32

In [172]:
df[["App", "Arquiterura"]] = df.App.apply(arq).apply(pd.Series)

In [173]:
df

,Data,App,URL_Port,Status,msg,Arquiterura
0,2015-10-30 16:49:06,chrome.exe,proxy.cse.cuhk.edu.hk:5070,open,through proxy proxy.cse.cuhk.edu.hk:5070 HTTPS,32
1,2015-10-30 16:49:06,chrome.exe,proxy.cse.cuhk.edu.hk:5070,open,through proxy proxy.cse.cuhk.edu.hk:5070 HTTPS,32
2,2015-10-30 16:49:06,chrome.exe,proxy.cse.cuhk.edu.hk:5070,open,through proxy proxy.cse.cuhk.edu.hk:5070 HTTPS,32
3,2015-10-30 16:49:07,chrome.exe,proxy.cse.cuhk.edu.hk:5070,close,"0 bytes sent, 0 bytes received, lifetime 00:01",32
4,2015-10-30 16:49:07,chrome.exe,proxy.cse.cuhk.edu.hk:5070,open,through proxy proxy.cse.cuhk.edu.hk:5070 HTTPS,32
...,...,...,...,...,...,...
1995,2015-07-27 10:23:30,chrome.exe,cpro.baidustatic.com:443,close,"334 bytes sent, 3713 bytes (3.62 KB) received,...",64
1996,2015-07-27 10:23:30,chrome.exe,q1.cnzz.com:80,open,through proxy proxy.cse.cuhk.edu.hk:5070 HTTPS,64
1997,2015-07-27 10:23:42,chrome.exe,t12.baidu.com:80,close,"0 bytes sent, 0 bytes received, lifetime 00:17",64
1998,2015-07-27 10:23:42,chrome.exe,mhfm9.us.cdndm5.com:80,close,"0 bytes sent, 0 bytes received, lifetime 00:12",64
1999,2015-07-27 10:23:42,chrome.exe,t12.baidu.com:80,close,"0 bytes sent, 0 bytes received, lifetime 00:17",64

In [174]:
df[df.Arquiterura == "64"]

,Data,App,URL_Port,Status,msg,Arquiterura
153,2015-10-30 16:51:56,svchost.exe,proxy.cse.cuhk.edu.hk:5070,close,"303 bytes sent, 275 bytes received, lifetime <...",64
157,2015-10-30 16:52:25,svchost.exe,proxy.cse.cuhk.edu.hk:5070,close,"301 bytes sent, 278 bytes received, lifetime <...",64
428,2015-10-30 17:59:03,svchost.exe,proxy.cse.cuhk.edu.hk:5070,close,"293 bytes sent, 514 bytes received, lifetime <...",64
904,2015-10-30 21:08:03,spoolsv.exe,127.0.0.1:135,error,Could not connect through proxy proxy.cse.cuhk...,64
918,2015-10-30 21:13:23,spoolsv.exe,127.0.0.1:135,error,Could not connect through proxy proxy.cse.cuhk...,64
...,...,...,...,...,...,...
1995,2015-07-27 10:23:30,chrome.exe,cpro.baidustatic.com:443,close,"334 bytes sent, 3713 bytes (3.62 KB) received,...",64
1996,2015-07-27 10:23:30,chrome.exe,q1.cnzz.com:80,open,through proxy proxy.cse.cuhk.edu.hk:5070 HTTPS,64
1997,2015-07-27 10:23:42,chrome.exe,t12.baidu.com:80,close,"0 bytes sent, 0 bytes received, lifetime 00:17",64
1998,2015-07-27 10:23:42,chrome.exe,mhfm9.us.cdndm5.com:80,close,"0 bytes sent, 0 bytes received, lifetime 00:12",64
1999,2015-07-27 10:23:42,chrome.exe,t12.baidu.com:80,close,"0 bytes sent, 0 bytes received, lifetime 00:17",64

In [175]:
aux = "chrome.exe *64"

aux.split("*")

['chrome.exe ', '64']

In [176]:
df.columns

Index(['Data', 'App', 'URL_Port', 'Status', 'msg', 'Arquiterura'], dtype='str')

In [177]:
df = df.rename(columns={"URL_Port": "URL_Origem"})

In [178]:
df.columns

Index(['Data', 'App', 'URL_Origem', 'Status', 'msg', 'Arquiterura'], dtype='str')

In [179]:
def set_origem(data:str):
    return data.split(":")
    pass

In [180]:
# df[["URL_Origem", "Port_Origem"]] = df.URL_Origem.apply(set_origem).apply(pd.Series)

In [181]:
df

,Data,App,URL_Origem,Status,msg,Arquiterura
0,2015-10-30 16:49:06,chrome.exe,proxy.cse.cuhk.edu.hk:5070,open,through proxy proxy.cse.cuhk.edu.hk:5070 HTTPS,32
1,2015-10-30 16:49:06,chrome.exe,proxy.cse.cuhk.edu.hk:5070,open,through proxy proxy.cse.cuhk.edu.hk:5070 HTTPS,32
2,2015-10-30 16:49:06,chrome.exe,proxy.cse.cuhk.edu.hk:5070,open,through proxy proxy.cse.cuhk.edu.hk:5070 HTTPS,32
3,2015-10-30 16:49:07,chrome.exe,proxy.cse.cuhk.edu.hk:5070,close,"0 bytes sent, 0 bytes received, lifetime 00:01",32
4,2015-10-30 16:49:07,chrome.exe,proxy.cse.cuhk.edu.hk:5070,open,through proxy proxy.cse.cuhk.edu.hk:5070 HTTPS,32
...,...,...,...,...,...,...
1995,2015-07-27 10:23:30,chrome.exe,cpro.baidustatic.com:443,close,"334 bytes sent, 3713 bytes (3.62 KB) received,...",64
1996,2015-07-27 10:23:30,chrome.exe,q1.cnzz.com:80,open,through proxy proxy.cse.cuhk.edu.hk:5070 HTTPS,64
1997,2015-07-27 10:23:42,chrome.exe,t12.baidu.com:80,close,"0 bytes sent, 0 bytes received, lifetime 00:17",64
1998,2015-07-27 10:23:42,chrome.exe,mhfm9.us.cdndm5.com:80,close,"0 bytes sent, 0 bytes received, lifetime 00:12",64
1999,2015-07-27 10:23:42,chrome.exe,t12.baidu.com:80,close,"0 bytes sent, 0 bytes received, lifetime 00:17",64

In [182]:
df[["URL_Origem", "Port_Origem"]] = df.URL_Origem.str.split(":", expand=True)

In [183]:
df

,Data,App,URL_Origem,Status,msg,Arquiterura,Port_Origem
0,2015-10-30 16:49:06,chrome.exe,proxy.cse.cuhk.edu.hk,open,through proxy proxy.cse.cuhk.edu.hk:5070 HTTPS,32,5070
1,2015-10-30 16:49:06,chrome.exe,proxy.cse.cuhk.edu.hk,open,through proxy proxy.cse.cuhk.edu.hk:5070 HTTPS,32,5070
2,2015-10-30 16:49:06,chrome.exe,proxy.cse.cuhk.edu.hk,open,through proxy proxy.cse.cuhk.edu.hk:5070 HTTPS,32,5070
3,2015-10-30 16:49:07,chrome.exe,proxy.cse.cuhk.edu.hk,close,"0 bytes sent, 0 bytes received, lifetime 00:01",32,5070
4,2015-10-30 16:49:07,chrome.exe,proxy.cse.cuhk.edu.hk,open,through proxy proxy.cse.cuhk.edu.hk:5070 HTTPS,32,5070
...,...,...,...,...,...,...,...
1995,2015-07-27 10:23:30,chrome.exe,cpro.baidustatic.com,close,"334 bytes sent, 3713 bytes (3.62 KB) received,...",64,443
1996,2015-07-27 10:23:30,chrome.exe,q1.cnzz.com,open,through proxy proxy.cse.cuhk.edu.hk:5070 HTTPS,64,80
1997,2015-07-27 10:23:42,chrome.exe,t12.baidu.com,close,"0 bytes sent, 0 bytes received, lifetime 00:17",64,80
1998,2015-07-27 10:23:42,chrome.exe,mhfm9.us.cdndm5.com,close,"0 bytes sent, 0 bytes received, lifetime 00:12",64,80
1999,2015-07-27 10:23:42,chrome.exe,t12.baidu.com,close,"0 bytes sent, 0 bytes received, lifetime 00:17",64,80

In [184]:
df[df.Status == "close"]

,Data,App,URL_Origem,Status,msg,Arquiterura,Port_Origem
3,2015-10-30 16:49:07,chrome.exe,proxy.cse.cuhk.edu.hk,close,"0 bytes sent, 0 bytes received, lifetime 00:01",32,5070
7,2015-10-30 16:49:07,chrome.exe,proxy.cse.cuhk.edu.hk,close,"403 bytes sent, 426 bytes received, lifetime <...",32,5070
10,2015-10-30 16:49:07,chrome.exe,proxy.cse.cuhk.edu.hk,close,"451 bytes sent, 18846 bytes (18.4 KB) received...",32,5070
11,2015-10-30 16:49:08,chrome.exe,proxy.cse.cuhk.edu.hk,close,"445 bytes sent, 5174 bytes (5.05 KB) received,...",32,5070
13,2015-10-30 16:49:08,chrome.exe,proxy.cse.cuhk.edu.hk,close,"1190 bytes (1.16 KB) sent, 1671 bytes (1.63 KB...",32,5070
...,...,...,...,...,...,...,...
1994,2015-07-27 10:23:30,chrome.exe,wn.pos.baidu.com,close,"330 bytes sent, 4169 bytes (4.07 KB) received,...",64,443
1995,2015-07-27 10:23:30,chrome.exe,cpro.baidustatic.com,close,"334 bytes sent, 3713 bytes (3.62 KB) received,...",64,443
1997,2015-07-27 10:23:42,chrome.exe,t12.baidu.com,close,"0 bytes sent, 0 bytes received, lifetime 00:17",64,80
1998,2015-07-27 10:23:42,chrome.exe,mhfm9.us.cdndm5.com,close,"0 bytes sent, 0 bytes received, lifetime 00:12",64,80
1999,2015-07-27 10:23:42,chrome.exe,t12.baidu.com,close,"0 bytes sent, 0 bytes received, lifetime 00:17",64,80