In [63]:
import pandas as pd
from utils import tratar_linha

In [64]:
raw_data_file = "Proxifier_2k.log"

In [65]:
linha = "[10.30 20:55:49] Yodao-Dict.exe - oimagea5.ydstatic.com:80 error : A connection request was canceled before the completion. "

tratar_linha(linha, 2025)

'2025.10.30 20:55:49;Yodao-Dict.exe;oimagea5.ydstatic.com:80;error;A connection request was canceled before the completion. '

In [66]:
with open(raw_data_file, "r") as origem, open("log.csv", "w") as destino:
    for linha in origem:
        destino.write(tratar_linha(linha))

In [67]:
df = pd.read_csv("log.csv",
                 sep=";",
                 names=["Data", "App","URL_Port","Status", "msg"],
                index_col=False
                 )
df.head()

,Data,App,URL_Port,Status,msg
0,2015.10.30 16:49:06,chrome.exe,proxy.cse.cuhk.edu.hk:5070,open,through proxy proxy.cse.cuhk.edu.hk:5070 HTTPS
1,2015.10.30 16:49:06,chrome.exe,proxy.cse.cuhk.edu.hk:5070,open,through proxy proxy.cse.cuhk.edu.hk:5070 HTTPS
2,2015.10.30 16:49:06,chrome.exe,proxy.cse.cuhk.edu.hk:5070,open,through proxy proxy.cse.cuhk.edu.hk:5070 HTTPS
3,2015.10.30 16:49:07,chrome.exe,proxy.cse.cuhk.edu.hk:5070,close,"0 bytes sent, 0 bytes received, lifetime 00:01"
4,2015.10.30 16:49:07,chrome.exe,proxy.cse.cuhk.edu.hk:5070,open,through proxy proxy.cse.cuhk.edu.hk:5070 HTTPS

In [68]:
df.dtypes

Data        str
App         str
URL_Port    str
Status      str
msg         str
dtype: object

In [69]:
df.Data = pd.to_datetime(df.Data, format="%Y.%m.%d %H:%M:%S")

In [70]:
df.head(2)

,Data,App,URL_Port,Status,msg
0,2015-10-30 16:49:06,chrome.exe,proxy.cse.cuhk.edu.hk:5070,open,through proxy proxy.cse.cuhk.edu.hk:5070 HTTPS
1,2015-10-30 16:49:06,chrome.exe,proxy.cse.cuhk.edu.hk:5070,open,through proxy proxy.cse.cuhk.edu.hk:5070 HTTPS

In [71]:
df.dtypes

Data        datetime64[us]
App                    str
URL_Port               str
Status                 str
msg                    str
dtype: object

In [72]:
df.Status.unique()

<StringArray>
['open', 'close', 'error']
Length: 3, dtype: str

In [73]:
df[df.Status == '-']

Empty DataFrame
Columns: [Data, App, URL_Port, Status, msg]
Index: []

'chrome.exe *64 <=> 'chrome.exe

In [74]:
df.App.unique()

<StringArray>
[                      'chrome.exe',                  'svchost.exe *64',
                      'Dropbox.exe',                          'Wiz.exe',
                       'WeChat.exe',                        'putty.exe',
                   'SogouCloud.exe',                           'QQ.exe',
                    'YodaoDict.exe',                'SGPicFaceTool.exe',
                   'QQExternal.exe',                      'firefox.exe',
             'git-remote-https.exe', 'FlashPlayerPlugin_18_0_0_209.exe',
                       'GitHub.exe',                        'Skype.exe',
                  'spoolsv.exe *64',                     'AcroRd32.exe',
                   'chrome.exe *64',                       'SGTool.exe',
                      'Acrobat.exe',                    'MobaXterm.exe',
                 'GoogleUpdate.exe',           'TeamViewer_Service.exe',
            'HiSuiteDownLoader.exe',                        '360AP.exe',
                    'tencentdl.exe',                     'QQPlayer.exe',
                'BSvcProcessor.exe',              'msfeedssync.exe *64',
                 'QQProtectUpd.exe',                     'SohuNews.exe']
Length: 32, dtype: str

In [79]:
def arq(app:str, sep="*"):
    if app.__contains__(sep):
        aux = app.split(sep)
        return aux[1]
    else:
        return 32

In [76]:
df["Arquiterura"] = df.App.apply(arq)

In [80]:
df[df.Arquiterura == "64"]

,Data,App,URL_Port,Status,msg,Arquiterura
153,2015-10-30 16:51:56,svchost.exe *64,proxy.cse.cuhk.edu.hk:5070,close,"303 bytes sent, 275 bytes received, lifetime <...",64
157,2015-10-30 16:52:25,svchost.exe *64,proxy.cse.cuhk.edu.hk:5070,close,"301 bytes sent, 278 bytes received, lifetime <...",64
428,2015-10-30 17:59:03,svchost.exe *64,proxy.cse.cuhk.edu.hk:5070,close,"293 bytes sent, 514 bytes received, lifetime <...",64
904,2015-10-30 21:08:03,spoolsv.exe *64,127.0.0.1:135,error,Could not connect through proxy proxy.cse.cuhk...,64
918,2015-10-30 21:13:23,spoolsv.exe *64,127.0.0.1:135,error,Could not connect through proxy proxy.cse.cuhk...,64
...,...,...,...,...,...,...
1995,2015-07-27 10:23:30,chrome.exe *64,cpro.baidustatic.com:443,close,"334 bytes sent, 3713 bytes (3.62 KB) received,...",64
1996,2015-07-27 10:23:30,chrome.exe *64,q1.cnzz.com:80,open,through proxy proxy.cse.cuhk.edu.hk:5070 HTTPS,64
1997,2015-07-27 10:23:42,chrome.exe *64,t12.baidu.com:80,close,"0 bytes sent, 0 bytes received, lifetime 00:17",64
1998,2015-07-27 10:23:42,chrome.exe *64,mhfm9.us.cdndm5.com:80,close,"0 bytes sent, 0 bytes received, lifetime 00:12",64
1999,2015-07-27 10:23:42,chrome.exe *64,t12.baidu.com:80,close,"0 bytes sent, 0 bytes received, lifetime 00:17",64

In [78]:
aux = "chrome.exe *64"

aux.split("*9ooo")

['chrome.exe *64']