In [ ]:
# !pip install pandas
# !pip inslall polars

In [2]:
import pandas as pd
import polars as pl

In [8]:
df = pd.read_csv("log.csv")

In [5]:
df_pl = pl.read_csv("log.csv")

In [9]:
df.size # 60 000 000

60000000

In [10]:
df.dtypes

timestamp            object
source_ip            object
dest_ip              object
protocol             object
action               object
threat_label         object
log_type             object
bytes_transferred     int64
user_agent           object
request_path         object
dtype: object

In [11]:
df.columns

Index(['timestamp', 'source_ip', 'dest_ip', 'protocol', 'action',
       'threat_label', 'log_type', 'bytes_transferred', 'user_agent',
       'request_path'],
      dtype='object')

In [12]:
df.shape # 6 000 000

(6000000, 10)

In [19]:
df.bytes_transferred.max()
df.bytes_transferred.min()

100

In [21]:
df.head()
df.tail()

,timestamp,source_ip,dest_ip,protocol,action,threat_label,log_type,bytes_transferred,user_agent,request_path
5999995,2024-06-06T00:00:00,235.165.118.37,192.168.1.60,SSH,blocked,suspicious,ids,44090,curl/7.64.1,/root?phpmyadmin
5999996,2024-11-14T00:00:00,192.168.1.107,192.168.1.192,TCP,allowed,benign,ids,26602,Nmap Scripting Engine,/
5999997,2024-03-31T00:00:00,192.168.1.131,192.168.1.49,TCP,allowed,benign,application,39058,Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...,/
5999998,2024-06-26T00:00:00,192.168.1.4,192.168.1.247,TCP,blocked,benign,ids,4519,curl/7.64.1,/
5999999,2024-03-21T00:00:00,59.151.57.2,192.168.1.47,TCP,allowed,benign,application,42132,Nmap Scripting Engine,/

In [23]:
df.action.value_counts()

action
allowed    3000646
blocked    2999354
Name: count, dtype: int64

In [24]:
df.log_type.value_counts()

log_type
application    2001768
ids            1999556
firewall       1998676
Name: count, dtype: int64

In [25]:
df.user_agent.value_counts()

user_agent
curl/7.64.1                                                                                                              1200739
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36          1200722
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/535.11 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36    1200062
Nmap Scripting Engine                                                                                                    1199655
SQLMap/1.6-dev                                                                                                           1198822
Name: count, dtype: int64

In [32]:
campo = "SQLMap/1.6-dev"

In [33]:
my_df = df[df.user_agent.str.contains(campo)].filter()

In [34]:
my_df.action.value_counts()

action
allowed    600165
blocked    598657
Name: count, dtype: int64

In [35]:
 my_df.threat_label.value_counts()

threat_label
benign        1102560
suspicious      71939
malicious       24323
Name: count, dtype: int64

In [37]:
df.head()

,timestamp,source_ip,dest_ip,protocol,action,threat_label,log_type,bytes_transferred,user_agent,request_path
0,2024-05-01T00:00:00,192.168.1.125,192.168.1.124,TCP,blocked,benign,firewall,10889,Nmap Scripting Engine,/
1,2024-07-18T00:00:00,192.168.1.201,192.168.1.201,ICMP,blocked,benign,application,36522,Nmap Scripting Engine,/
2,2024-04-07T00:00:00,192.168.1.248,192.168.1.15,HTTP,allowed,benign,application,20652,Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...,/login
3,2024-10-26T00:00:00,192.168.1.236,192.168.1.219,HTTP,allowed,benign,application,5350,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7...,/login
4,2024-10-31T00:00:00,192.168.1.221,192.168.1.61,ICMP,allowed,benign,application,40691,Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...,/

In [48]:
df[ df.source_ip.str.contains("192.168.1") ]

,timestamp,source_ip,dest_ip,protocol,action,threat_label,log_type,bytes_transferred,user_agent,request_path
0,2024-05-01T00:00:00,192.168.1.125,192.168.1.124,TCP,blocked,benign,firewall,10889,Nmap Scripting Engine,/
1,2024-07-18T00:00:00,192.168.1.201,192.168.1.201,ICMP,blocked,benign,application,36522,Nmap Scripting Engine,/
2,2024-04-07T00:00:00,192.168.1.248,192.168.1.15,HTTP,allowed,benign,application,20652,Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...,/login
3,2024-10-26T00:00:00,192.168.1.236,192.168.1.219,HTTP,allowed,benign,application,5350,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7...,/login
4,2024-10-31T00:00:00,192.168.1.221,192.168.1.61,ICMP,allowed,benign,application,40691,Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...,/
...,...,...,...,...,...,...,...,...,...,...
5999991,2024-01-08T00:00:00,192.168.1.193,192.168.1.224,HTTPS,allowed,benign,application,26982,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7...,/secure
5999994,2024-03-01T00:00:00,192.168.1.55,192.168.1.148,TCP,allowed,benign,application,6097,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7...,/
5999996,2024-11-14T00:00:00,192.168.1.107,192.168.1.192,TCP,allowed,benign,ids,26602,Nmap Scripting Engine,/
5999997,2024-03-31T00:00:00,192.168.1.131,192.168.1.49,TCP,allowed,benign,application,39058,Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...,/
5999998,2024-06-26T00:00:00,192.168.1.4,192.168.1.247,TCP,blocked,benign,ids,4519,curl/7.64.1,/

In [55]:
df[df.action == "blocked"]

,timestamp,source_ip,dest_ip,protocol,action,threat_label,log_type,bytes_transferred,user_agent,request_path
0,2024-05-01T00:00:00,192.168.1.125,192.168.1.124,TCP,blocked,benign,firewall,10889,Nmap Scripting Engine,/
1,2024-07-18T00:00:00,192.168.1.201,192.168.1.201,ICMP,blocked,benign,application,36522,Nmap Scripting Engine,/
7,2024-02-07T00:00:00,192.168.1.130,192.168.1.68,TCP,blocked,benign,firewall,16109,curl/7.64.1,/
10,2024-06-24T00:00:00,192.168.1.163,192.168.1.219,UDP,blocked,benign,ids,3429,Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...,/
11,2024-05-21T00:00:00,192.168.1.86,192.168.1.198,TCP,blocked,benign,firewall,48677,Nmap Scripting Engine,/
...,...,...,...,...,...,...,...,...,...,...
5999989,2024-11-06T00:00:00,192.168.1.236,192.168.1.25,TCP,blocked,benign,application,28577,Nmap Scripting Engine,/
5999992,2024-08-17T00:00:00,168.128.102.227,192.168.1.17,UDP,blocked,suspicious,ids,44138,curl/7.64.1,/?phpmyadmin
5999993,2024-01-16T00:00:00,109.106.120.222,192.168.1.60,HTTP,blocked,suspicious,firewall,19670,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7...,/admin?..\..\etc\passwd
5999995,2024-06-06T00:00:00,235.165.118.37,192.168.1.60,SSH,blocked,suspicious,ids,44090,curl/7.64.1,/root?phpmyadmin
5999998,2024-06-26T00:00:00,192.168.1.4,192.168.1.247,TCP,blocked,benign,ids,4519,curl/7.64.1,/

In [66]:
df[['source_ip', 'action', 'protocol']].value_counts()

source_ip       action   protocol
96.196.42.139   allowed  TCP         2403
88.72.40.56     blocked  TCP         2395
208.223.2.195   allowed  TCP         2355
144.138.68.192  blocked  TCP         2351
177.52.183.80   allowed  TCP         2349
                                     ...
192.168.1.58    allowed  FTP          359
192.168.1.137   blocked  FTP          357
192.168.1.9     allowed  FTP          355
192.168.1.74    allowed  SSH          351
192.168.1.63    allowed  FTP          350
Name: count, Length: 4956, dtype: int64